### PR TITLE
164594275 user sign up page

### PR DESCRIPTION
**Pull request by Ivankivu**
This PR updates develop-branch with newly modified content from the 64594275-user-sign-up-page branch. As seen below a graphic image displaying the activity for the user signup page
Screenshot from 2019-03-13 17-37-56

### CODE REVIEW

**Comment by bekeplar** [comment]
Nice progress brother. Though kindly consider guideline number 3 on challenge one.

**Comment by Ivankivu** [comment]
@bekeplar Thank you for that correction.

**Comment by alexxsanya** [comment]
@Ivankivu I suggest you use javascript to generate the <option> tag for year field in the signup.html, so that years below current years are not show and you don't always have to edit that lines of code manually

**Comment by Ivankivu** [comment]
> @Ivankivu I suggest you use javascript to generate the tag for year field in the signup.html so that years below current years do not show and you don't always have to edit that lines of code manually

@alexxsanya Thanks. This helped out a lot

**Comment by ghost** [comment]
Hallo @Ivankivu, apart from feed back from alexsanya and bekeplar, I like your UI

**Pull request merged**
